@startuml
!define RECTANGLE class

skinparam stereotypeDisplay none

hide stereotype
skinparam minClassWidth 100
skinparam nodesep 20
skinparam ranksep 5
'skinparam packageStyle rectangle
'skinparam linetype ortho
'skinparam arrowThickness 1


skinparam rectangle {
    BackgroundColor White
    BorderColor Black
}

skinparam rectangle<<dialect>> {
    BackgroundColor Yellow
    BorderColor Black
    FontColor Black
}

skinparam interface<<compilephase>> {
    BackgroundColor Red
    BorderColor Black
    FontColor Black
}

skinparam interface<<pass>> {
    BackgroundColor Green
    BorderColor Black
    FontColor Black
}

skinparam interface<<conversion>> {
    BackgroundColor DarkBlue
    BorderColor Black
    FontColor Black
}

package "LayergroupPass" {
    () "groupSearch" <<pass>>
    () "CascadePass" <<pass>>
    () "hwSchedulePass" <<pass>>
    () "SRAMMallocPass" <<pass>>
    () "AssignHardwarePass" <<pass>>
    () "AssignTensorInfoPass" <<pass>>

    groupSearch --> AssignTensorInfoPass
    AssignTensorInfoPass --> AssignHardwarePass
    AssignHardwarePass --> CascadePass
    CascadePass --> hwSchedulePass
    hwSchedulePass --> SRAMMallocPass
}

rectangle "hal dialect" as hal <<dialect>>
rectangle "model for certain target" as model_for_certain_target


() "HAL" as HAL <<compilephase>>
() "HAL_OPTED" as HAL_OPTED <<compilephase>>
() "HAL_ADDRESSED" as HAL_ADDRESSED <<compilephase>>
() "CODEGEN" as CODEGEN <<compilephase>>

() "LegalizePass" as LegalizePass <<pass>>
() "HalTargetDependentPass" as HalTargetDependentPass <<pass>>
' () "LayergroupPass" as LayergroupPass <<pass>>
() "InsertSyncPass" as InsertSyncPass <<pass>>
() "weightPackPass" as weightPackPass <<pass>>
() "AssemblePass" as AssemblePass <<pass>>
() "HalTargetVerfiyPass" as HalTargetVerfiyPass <<pass>>
() "CodegenPass" as CodegenPass <<conversion>>

' 连接关系

hal -> HAL
HAL -> LegalizePass
LegalizePass --> HalTargetDependentPass 
HalTargetDependentPass --> HAL_OPTED
HAL_OPTED --> LayergroupPass
LayergroupPass --> InsertSyncPass
InsertSyncPass --> HAL_ADDRESSED
HAL_ADDRESSED --> HalTargetVerfiyPass
HalTargetVerfiyPass --> weightPackPass
weightPackPass --> AssemblePass
AssemblePass --> CODEGEN
CODEGEN -left-> CodegenPass
CodegenPass --> model_for_certain_target : codegen

@enduml
